In [1]:
#!pip install numpy (# symbol denotes comments, remove it to run the code)

In [2]:
import numpy as np 

# Array Creation

In [3]:
arr1 = np.array([1,2,3]) # 1 Dimentional Array

In [4]:
arr1

array([1, 2, 3])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape # (rows, columns)

(3,)

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr2 = np.arange(0,10,2)

In [9]:
arr2

array([0, 2, 4, 6, 8])

In [10]:
type(arr2)

numpy.ndarray

In [11]:
arr2.shape

(5,)

In [12]:
arr3 = np.random.rand(4, )

In [13]:
arr3

array([0.99447997, 0.5313913 , 0.46627811, 0.69569626])

In [14]:
type(arr3)

numpy.ndarray

In [15]:
arr3.shape

(4,)

In [16]:
arr3.dtype

dtype('float64')

In [17]:
arr4 = np.random.randn(4, ) # Normally distributed

In [18]:
arr4

array([-0.13091849, -0.21576675,  1.36355393,  2.6446852 ])

In [19]:
type(arr4)

numpy.ndarray

In [20]:
arr4.shape

(4,)

In [21]:
arr4.dtype

dtype('float64')

In [22]:
arr5 = np.linspace(0,10,10)

In [23]:
arr5

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [24]:
type(arr5)

numpy.ndarray

In [25]:
arr5.shape

(10,)

In [26]:
arr5.dtype

dtype('float64')

In [27]:
a = [[1.0, 3.0, 4.0],[5.0, 6,7]] # 2 Dimentional Array

In [28]:
arr6 = np.array(a)

In [29]:
arr6

array([[1., 3., 4.],
       [5., 6., 7.]])

In [30]:
type(arr6)

numpy.ndarray

In [31]:
arr6.shape 

(2, 3)

In [32]:
arr6.dtype

dtype('float64')

In [33]:
arr7 = np.random.rand(4, 2)

In [34]:
arr7

array([[0.17721337, 0.0951708 ],
       [0.81144717, 0.55355541],
       [0.68227519, 0.45080898],
       [0.75295596, 0.70372509]])

In [35]:
type(arr7)

numpy.ndarray

In [36]:
arr7.shape

(4, 2)

In [37]:
arr7.dtype

dtype('float64')

In [38]:
arr8 = np.identity(5)

In [39]:
arr8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
type(arr8)

numpy.ndarray

In [41]:
arr8.shape

(5, 5)

In [42]:
arr8.dtype

dtype('float64')

In [43]:
arr9 = np.empty((4,6))

In [44]:
arr9

array([[1.23e-321, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]])

In [45]:
arr10 = np.empty_like(arr7)

In [46]:
arr10

array([[0.17721337, 0.0951708 ],
       [0.81144717, 0.55355541],
       [0.68227519, 0.45080898],
       [0.75295596, 0.70372509]])

In [47]:
arr11 = np.zeros((2, 4, 3))

In [48]:
arr11

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# Array Elements Accessing

In [49]:
arr1

array([1, 2, 3])

In [50]:
print(arr1[0])
print(arr1[1])
print(arr1[2])

1
2
3


In [51]:
arr10

array([[0.17721337, 0.0951708 ],
       [0.81144717, 0.55355541],
       [0.68227519, 0.45080898],
       [0.75295596, 0.70372509]])

In [52]:
# [row,column]
print(arr10[0,1])
print(arr10[1,0])
print(arr10[2,1])

0.09517079676711826
0.811447174739628
0.4508089797685828


In [53]:
arr10[1:]

array([[0.81144717, 0.55355541],
       [0.68227519, 0.45080898],
       [0.75295596, 0.70372509]])

In [54]:
arr10[1:2]

array([[0.81144717, 0.55355541]])

In [55]:
for elements in arr1:
    print(elements)

1
2
3


In [56]:
for row,column in arr10:
    print(row)
    print(column)

0.17721337224826794
0.09517079676711826
0.811447174739628
0.5535554145277609
0.6822751942790884
0.4508089797685828
0.7529559631474915
0.7037250937384254


# Replacing Elements

In [57]:
arr2

array([0, 2, 4, 6, 8])

In [58]:
arr2[2] = 90 # Replace 3rd 4 element by 90

In [59]:
arr2

array([ 0,  2, 90,  6,  8])

In [60]:
arr6

array([[1., 3., 4.],
       [5., 6., 7.]])

In [61]:
arr6[0,2]=22

In [62]:
arr6

array([[ 1.,  3., 22.],
       [ 5.,  6.,  7.]])

# Reshaping Array

In [63]:
arr2

array([ 0,  2, 90,  6,  8])

In [64]:
arr2.shape

(5,)

In [65]:
reshape = arr2.reshape(5,1)

In [66]:
reshape

array([[ 0],
       [ 2],
       [90],
       [ 6],
       [ 8]])

In [67]:
reshape.shape

(5, 1)

In [68]:
transpose = reshape.T

In [69]:
transpose

array([[ 0,  2, 90,  6,  8]])

In [70]:
transpose.shape

(1, 5)

In [71]:
arr7

array([[0.17721337, 0.0951708 ],
       [0.81144717, 0.55355541],
       [0.68227519, 0.45080898],
       [0.75295596, 0.70372509]])

In [72]:
arr7.shape

(4, 2)

In [73]:
flatten = arr7.flatten() # Multi dimension to 1D

In [74]:
flatten

array([0.17721337, 0.0951708 , 0.81144717, 0.55355541, 0.68227519,
       0.45080898, 0.75295596, 0.70372509])

In [75]:
flatten.shape

(8,)

In [76]:
flatten[2]=2.0

In [77]:
flatten

array([0.17721337, 0.0951708 , 2.        , 0.55355541, 0.68227519,
       0.45080898, 0.75295596, 0.70372509])

In [78]:
arr7 # flatten does not affect original array

array([[0.17721337, 0.0951708 ],
       [0.81144717, 0.55355541],
       [0.68227519, 0.45080898],
       [0.75295596, 0.70372509]])

In [79]:
rav = arr7.ravel()

In [80]:
rav

array([0.17721337, 0.0951708 , 0.81144717, 0.55355541, 0.68227519,
       0.45080898, 0.75295596, 0.70372509])

In [81]:
rav[2]=2.0

In [82]:
rav

array([0.17721337, 0.0951708 , 2.        , 0.55355541, 0.68227519,
       0.45080898, 0.75295596, 0.70372509])

In [83]:
rav.ndim

1

In [84]:
arr7 # Originl Array gets changed

array([[0.17721337, 0.0951708 ],
       [2.        , 0.55355541],
       [0.68227519, 0.45080898],
       [0.75295596, 0.70372509]])

In [85]:
arr7.ndim

2

# Methods and Attributes

In [86]:
arr3

array([0.99447997, 0.5313913 , 0.46627811, 0.69569626])

In [87]:
arr3.min() # Returns min Value

0.4662781077588676

In [88]:
arr3.argmin() # Returns Index of min Value 

2

In [89]:
arr3.max() # Returns max Value

0.9944799735886402

In [90]:
arr3.argmax() # Returns Index of max Value 

0

In [91]:
arr2

array([ 0,  2, 90,  6,  8])

In [92]:
s = arr2.argsort() # Returns indices of sorting order

In [93]:
s

array([0, 1, 3, 4, 2], dtype=int64)

In [94]:
arr2.sort() # sorts the values

In [95]:
arr2

array([ 0,  2,  6,  8, 90])

In [96]:
np.sqrt(arr2)

array([0.        , 1.41421356, 2.44948974, 2.82842712, 9.48683298])

In [97]:
arr2

array([ 0,  2,  6,  8, 90])

In [98]:
np.where(arr2>2)

(array([2, 3, 4], dtype=int64),)

In [99]:
np.count_nonzero(arr2)

4

### https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html

# Memory Management

In [100]:
l =[]
for i in range (0,100,1):
    l.append(i)

In [101]:
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [102]:
nump = np.arange(0,100,1)

In [103]:
nump

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [104]:
import sys

In [105]:
sys.getsizeof(l[0])*len(l) # Memory consumption of list array

2400

In [106]:
nump.itemsize*nump.size # Memory consumption of numpy array

400

In [107]:
reduced_bytes = np.arange(0,100,1, dtype=np.int8)

In [108]:
reduced_bytes

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int8)

In [109]:
reduced_bytes.itemsize*reduced_bytes.size # Memory consumption of numpy array with smaller dtype

100

# Statistical Maths

In [110]:
x = reduced_bytes.reshape(10,10)

In [111]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]], dtype=int8)

In [112]:
x.mean()

49.5

In [113]:
x.std()

28.86607004772212

In [114]:
x.mean(axis=1)

array([ 4.5, 14.5, 24.5, 34.5, 44.5, 54.5, 64.5, 74.5, 84.5, 94.5])

In [115]:
x.mean(axis=0)

array([45., 46., 47., 48., 49., 50., 51., 52., 53., 54.])

In [116]:
arr4

array([-0.13091849, -0.21576675,  1.36355393,  2.6446852 ])

In [117]:
arr3

array([0.99447997, 0.5313913 , 0.46627811, 0.69569626])

In [118]:
arr4+arr3

array([0.86356148, 0.31562455, 1.82983204, 3.34038146])

In [119]:
arr4*arr3

array([-0.13019582, -0.11465658,  0.63579535,  1.83989761])

In [120]:
arr4-arr3

array([-1.12539846, -0.74715806,  0.89727582,  1.94898893])

In [121]:
arr4/arr3

array([-0.13164518, -0.40604118,  2.92433616,  3.80149404])

In [122]:
arr4.dot(arr3) # dot product

2.230840561776766